# Generated by Django 2.0.13 on 2019-05-26 15:35

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TsunList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('UserId', models.IntegerField(editable=False)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('RE', '永久保存'), ('DAC', '終わったら消す'), ('DIT', '今日中に消す')], max_length=20)),
                ('tsuntype', models.CharField(choices=[('W', 'Web'), ('PD', 'PDF'), ('Pa', 'Paper')], max_length=20)),
                ('link', models.CharField(max_length=500)),
                ('memo', models.CharField(max_length=200)),
                ('exp', models.IntegerField(max_length=10000)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'tsun',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='ユーザー名')),
                ('password', models.CharField(blank=True, max_length=20, null=True, verbose_name='パスワード')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
