# Generated by Django 2.0.13 on 2019-05-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190527_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tsunlist',
            name='UserId',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='tsunlist',
            name='category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tsunlist',
            name='tsuntype',
            field=models.CharField(max_length=20),
        ),
    ]
